document.addEventListener('DOMContentLoaded', function () {
  const fades = document.querySelectorAll('.fade-up');
  setTimeout(() => fades.forEach(el => el.classList.add('visible')), 120);
  const toggle = document.querySelector('.menu-toggle');
  const nav = document.querySelector('.nav');
  toggle && toggle.addEventListener('click', () => { nav.style.display = (nav.style.display === 'flex') ? 'none' : 'flex'; });
  document.querySelectorAll('a[href^="#"]').forEach(a=>{ a.addEventListener('click', function(e){ const href=this.getAttribute('href'); if(href.startsWith('#')){ e.preventDefault(); const target=document.querySelector(href); if(target) target.scrollIntoView({behavior:'smooth',block:'start'}); } }); });
  const topBtn = document.getElementById('topBtn'); window.addEventListener('scroll', ()=>{ if(window.scrollY>300) topBtn.style.display='block'; else topBtn.style.display='none'; }); topBtn.addEventListener('click', ()=> window.scrollTo({top:0,behavior:'smooth'}));
});
function sendToViber(e){ e.preventDefault(); const name=document.getElementById('userName').value.trim(); const phone=document.getElementById('userPhone').value.trim(); const from=document.getElementById('userFrom').value.trim(); const to=document.getElementById('userTo').value.trim(); const message=document.getElementById('userMessage').value.trim(); const text = encodeURIComponent(`🇺🇦 EuroWay — Пасажирські перевезення\n\n👤 Ім’я: ${name}\n📞 Телефон: ${phone}\n🏁 Звідки: ${from}\n🎯 Куди: ${to}\n💬 Хочу уточнити наявність місць та вартість поїздки.\n\nПовідомлення: ${message}`); const invite = `https://invite.viber.com/?g2=AQBXevxDf8qvr02hycsyOLunLh6dSXHJH8Uc01hOaeafmSe78OVyRIGzq9GeNQBb&text=${text}`; window.open(invite, '_blank'); const notice = document.getElementById('formNotice'); notice.innerText='✅ Заявку відправлено — зв\'яжемось з вами у Viber!'; notice.style.display='block'; document.getElementById('leadForm').reset(); return false; }